### ISSUE TITLE
Add `hacktoberfest` topic & label to the repo

### ISSUE THREAD

**Issue by oleg-nenashev** [jenkins-infra/cn.jenkins.io#12]
Chinese Localization SIG participates in the Hacktoberfest: https://jenkins.io/blog/2018/10/01/hacktoberfest/
It would be great to add a hacktoberfest label to the repo so that it appears on https://hacktoberfest.digitalocean.com/

CC @LinuxSuRen

**Comment by LinuxSuRen** [comment]
@oleg-nenashev I have no permission to do that yet.

**Comment by node** [comment]
Good idea , so who has permission to add the cool label to this issue ?  Let's hack !

**Comment by LinuxSuRen** [comment]
It's done.
