### ISSUE TITLE
Put the translator info into the blogs

### ISSUE THREAD

**Issue by LinuxSuRen** [jenkins-infra/cn.jenkins.io#126]
We should let the translated blogs have a clear tips that show it's a translated article instead of an original one. Suggest points:

* add the orignal article link
* add the translator github link

More discussions are welcome. And thanks for @oleg-nenashev giving these ideas.

**Comment by raychou1203** [comment]
Does every translator have his layout? 
In the other words,  should we push ourselves infro to this repo?

**Comment by LinuxSuRen** [comment]
You can submit your personal information into this repo. I think it's an optiona instead of necessary. But  every translated blog should have the translator's id.
