### ISSUE TITLE
jenkins.io can't switch language from Chinese

### ISSUE THREAD

**Issue by nathan-ca** [jenkins-infra/cn.jenkins.io#238]
When user visit https://jenkins.io, the browser was redirected to https://jenkins.io/zh/, user can't switch language at all.

**Comment by LinuxSuRen** [comment]
Thanks for reporting this problem.

**Comment by muellert** [comment]
Suggested fix: Change the nginx config line from 

     ~zh zh;

to
    ~^zh zh;

That should match only if Chinese is the most preferred language.

**Comment by LinuxSuRen** [comment]
@muellert Thank you for the advice.
