### ISSUE TITLE
升级指南存放的目录发生变更，中文网站是否也可以同步变更

### ISSUE THREAD

**Issue by zhaoying818** [jenkins-infra/cn.jenkins.io#287]
英文版的升级指南 存放在
[content/_data/upgrades/](!https://github.com/jenkins-infra/jenkins.io/blob/master/content/_data/upgrades/)

中文版的是否要跟进呢？》

**Comment by LinuxSuRen** [comment]
我觉得可以同步更新的👍

**Comment by yJunS** [comment]
+1

**Comment by zhaoying818** [comment]
初步实验已经 完成，改天做个同步就好了
@LinuxSuRen @yJunS 
![图片](https://user-images.githubusercontent.com/7424997/79775225-876a1280-8366-11ea-9ed4-c52d954618f2.png)

**Comment by yJunS** [comment]
目前看的话。应该还是有些资源没有完全加载，样式大部分都没显示出来

**Comment by zhaoying818** [comment]
![图片](https://user-images.githubusercontent.com/7424997/79891409-83f08d00-8433-11ea-9bff-4990f353b656.png)

![图片](https://user-images.githubusercontent.com/7424997/79891625-d7fb7180-8433-11ea-8aaf-9848df0b8d6e.png)

**Comment by yJunS** [comment]
![image](https://user-images.githubusercontent.com/20575981/79926229-f2067580-846e-11ea-9e4b-cc13368cd046.png)
![image](https://user-images.githubusercontent.com/20575981/79926246-faf74700-846e-11ea-99b6-3dc675a0f55f.png)
应该是这样的吧。

**Comment by zhaoying818** [comment]
> ![image](https://user-images.githubusercontent.com/20575981/79926229-f2067580-846e-11ea-9e4b-cc13368cd046.png)
> ![image](https://user-images.githubusercontent.com/20575981/79926246-faf74700-846e-11ea-99b6-3dc675a0f55f.png)
> 应该是这样的吧。

确实应该是这样子的！我这边有一些资源一直不能加载，所以显示会有一些问题
