### ISSUE TITLE
Add title for content/blog/2018/08/2018-08-21-contributor-summit-nice.adoc

### ISSUE THREAD

**Issue by raychou1203** [jenkins-infra/cn.jenkins.io#84]
https://github.com/jenkins-infra/cn.jenkins.io/blob/master/content/blog/2018/08/2018-08-21-contributor-summit-nice.adoc

https://jenkins.io/zh/blog/2018/08/21/contributor-summit-nice/#

It needs a title.

**Comment by andreafy** [comment]
emmm
